#SPDX-License-Identifier: MIT-0
---
# tasks file for ./roles/sshd-configs

- name: Deploy hardened SSH configuration from template
  become: true
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart SSH

- name: Nullify cloud-init SSH overrides
  become: true
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    state: absent
  notify: Restart SSH
