# SPDX-License-Identifier: MIT-0
---
- name: Explicitly run 'echo $SHELL'
  run_once: true
  ansible.builtin.command: echo $SHELL
  register: linux_security_local_shell_cmd
  changed_when: false
  become: false

- name: Ensure the target system user exists
  ansible.builtin.user:
    name: "{{ linux_security_authorized_key_user }}"
    shell: "{{ linux_security_local_shell_cmd.stdout | trim }}"
    groups: sudo
    append: true
    state: present
  become: true

- name: Set authorized keys from role file
  ansible.posix.authorized_key:
    user: "{{ linux_security_authorized_key_user }}"
    state: present
    key: "{{ lookup('file', linux_security_authorized_key_file) }}"
  become: true
