# SPDX-License-Identifier: MIT-0
---
- name: Set authorized keys from role file
  ansible.posix.authorized_key:
    user: "{{ linux_security_authorized_key_user }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', role_path + '/files/' + linux_security_authorized_key_file) }}"
  become: true
