# SPDX-License-Identifier: MIT-0
---
- name: Get installed goss version
  ansible.builtin.command: /usr/local/bin/goss --version
  register: linux_security_goss_installed_version
  changed_when: false
  failed_when: false
  become: true

- name: Download goss binary
  ansible.builtin.get_url:
    url: "{{ linux_security_goss_dl_url }}"
    dest: /usr/local/bin/goss
    mode: "0755"
    owner: root
    group: root
  become: true
  when: linux_security_goss_version not in linux_security_goss_installed_version.stdout

- name: Download dgoss wrapper
  ansible.builtin.get_url:
    url: "{{ linux_security_goss_dgoss_dl_url }}"
    dest: /usr/local/bin/dgoss
    mode: "0755"
    owner: root
    group: root
  become: true
  when: linux_security_goss_version not in linux_security_goss_installed_version.stdout
