# SPDX-License-Identifier: MIT-0
---
- name: Include baseline package tasks
  ansible.builtin.import_tasks: baseline.yml
  when: linux_security_enable_baseline | bool

- name: Include authorized keys tasks
  ansible.builtin.import_tasks: authorized_keys.yml
  when: linux_security_enable_authorized_keys | bool

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: sshd.yml
  when: linux_security_enable_sshd_hardening | bool

- name: Include UFW tasks
  ansible.builtin.import_tasks: ufw.yml
  when: linux_security_enable_ufw | bool

- name: Include Fail2Ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  when: linux_security_enable_fail2ban | bool

- name: Include Goss tasks
  ansible.builtin.import_tasks: goss.yml
  when: linux_security_enable_goss | bool
