# SPDX-License-Identifier: MIT-0
---
- name: Allow SSH on port over allowed interfaces {{ linux_security_ufw_ssh_port }}
  community.general.ufw:
    rule: allow
    port: "{{ linux_security_ufw_ssh_port }}"
    proto: tcp
    interface_in: "{{ item }}"
  loop: "{{ linux_security_ufw_allow_interfaces }}"
  become: true

- name: Deny SSH on port over disallowed interfaces {{ linux_security_ufw_ssh_port }}
  community.general.ufw:
    rule: deny
    port: "{{ linux_security_ufw_ssh_port }}"
    proto: tcp
    interface_in: "{{ item }}"
  loop: "{{ linux_security_ufw_deny_interfaces }}"
  become: true

- name: Enable UFW with default deny
  community.general.ufw:
    state: enabled
    policy: "{{ linux_security_ufw_default_incoming_policy }}"
    direction: incoming
  become: true
  # noqa: args[module]

- name: Gather the processor service facts
  ansible.builtin.service_facts:

- name: Permanently mask avahi services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: true
    state: stopped
  loop:
    - avahi-daemon.service
    - avahi-daemon.socket
  when: 
    - linux_security_disable_avahi | bool
    - item in services
  become: true

- name: Ensure UFW is enabled and running
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: true
  become: true
