# SPDX-License-Identifier: MIT-0
---
- name: Check if Zsh is installed on the target server
  ansible.builtin.stat:
    path: /bin/zsh
  register: zsh_check

- name: Create the local user account
  ansible.builtin.user:
    name: "{{ linux_security_user_name }}"
    comment: "{{ linux_security_user_comment }}"
    # Dynamically use Zsh if it exists, otherwise fall back to Bash
    shell: "{{ '/bin/zsh' if zsh_check.stat.exists else '/bin/bash' }}"
    groups: "{{ linux_security_user_groups | join(',') }}"
    append: true
    create_home: true
    home: "/home/{{ linux_security_user_name }}"
    state: present
  become: true

- name: Set permissions on the user home directory
  ansible.builtin.file:
    path: "/home/{{ linux_security_user_name }}"
    owner: "{{ linux_security_user_name }}"
    group: "{{ linux_security_user_name }}"
    mode: "0750"
    state: directory
  become: true

- name: Set up .ssh directory for the user
  ansible.builtin.file:
    path: "/home/{{ linux_security_user_name }}/.ssh"
    owner: "{{ linux_security_user_name }}"
    group: "{{ linux_security_user_name }}"
    mode: "0700"
    state: directory
  become: true

- name: Configure passwordless sudo for the user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ linux_security_user_name }}"
    owner: root
    group: root
    mode: "0440"
    content: |
      {{ linux_security_user_name }} ALL=(ALL) NOPASSWD:ALL
    validate: /usr/sbin/visudo -cf %s
  become: true
