#SPDX-License-Identifier: MIT-0
---
# tasks file for ./roles/pubkey

- name: Set authorized keys from role pubkey file
  ansible.posix.authorized_key:
    user: "{{ ansible_user | default(ansible_facts['user_id']) }}"
    state: present
    key: "{{ lookup('file', 'pubkey') }}"
