---
- name: Verify linux_neovim role
  hosts: all
  tasks:
    - name: Verify zsh is installed
      ansible.builtin.command: zsh --version
      register: linux_neovim_zsh_version
      changed_when: false
      failed_when: linux_neovim_zsh_version.rc != 0

    - name: Verify zshrc exists
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
      register: linux_neovim_zshrc_stat

    - name: Ensure zshrc file is present
      ansible.builtin.assert:
        that:
          - linux_neovim_zshrc_stat.stat.exists
