# SPDX-License-Identifier: MIT-0
---
- name: Include OS prerequisites tasks
  ansible.builtin.include_tasks: install.yml
  when: not linux_infisical_remove | bool

- name: Include removal tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: linux_infisical_remove | bool
