---
- name: Converge
  hosts: all
  become: true
  vars:
    linux_security_enable_ufw: true
    linux_security_enable_sshd_hardening: true
    linux_security_enable_fail2ban: true
    linux_security_enable_goss: true
  roles:
    - linux_security
