---
- name: Verify linux_security role
  hosts: all
  vars_files:
    - ../../../defaults/main.yml

  tasks:
    - name: Verify unattended-upgrades is installed
      ansible.builtin.command: unattended-upgrades --help
      register: linux_security_unattended_help
      changed_when: false
      failed_when: linux_security_unattended_help.rc != 0

    - name: Verify authorized_keys file exists
      ansible.builtin.stat:
        path: "/home/{{ linux_security_authorized_key_user | default('seeker') }}/.ssh/authorized_keys"
      register: linux_security_authorized_keys_stat

    - name: Ensure authorized_keys file is present
      ansible.builtin.assert:
        that:
          - linux_security_authorized_keys_stat.stat.exists

    - name: Verify Fail2Ban is installed
      ansible.builtin.command: fail2ban-client --version
      register: linux_security_fail2ban_version
      changed_when: false
      failed_when: linux_security_fail2ban_version.rc != 0

    - name: Verify Fail2Ban service is running
      ansible.builtin.service:
        name: fail2ban
        state: started
      register: linux_security_fail2ban_service
      # Bypasses checking the running state inside Docker containers
      when: ansible_virtualization_type != 'docker'

    - name: Ensure Fail2Ban sshd jail is active
      ansible.builtin.command: fail2ban-client status sshd
      register: linux_security_fail2ban_sshd_status
      changed_when: false
      failed_when: linux_security_fail2ban_sshd_status.rc != 0
      # Bypasses socket connectivity verification inside Docker containers
      when: ansible_virtualization_type != 'docker'
