---
- name: Verify linux_security role
  hosts: all
  tasks:
    - name: Verify unattended-upgrades is installed
      ansible.builtin.command: unattended-upgrades --help
      register: linux_security_unattended_help
      changed_when: false
      failed_when: linux_security_unattended_help.rc != 0

    - name: Verify authorized_keys file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      register: linux_security_authorized_keys_stat

    - name: Ensure authorized_keys file is present
      ansible.builtin.assert:
        that:
          - linux_security_authorized_keys_stat.stat.exists
