---
- name: Verify docker_compose_personal role
  hosts: all
  tasks:
    - name: Verify repository directory exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/docker"
      register: docker_compose_personal_repo_dir

    - name: Ensure repository directory is present
      ansible.builtin.assert:
        that:
          - docker_compose_personal_repo_dir.stat.exists
          - docker_compose_personal_repo_dir.stat.isdir
