# tasks file for ./roles/neovim-base

- name: "Install base dependencies for neovim"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - unzip
    - build-essential
    - fd-find
    - ripgrep
    - lazygit
    - fzf # needs 0.60+
    - tree-sitter-cli # needs 0.26.1+

- name: "Install Tmux"
  ansible.builtin.package:
    name: tmux
    state: present
# TODO: TMUX INSTALLATIONS
