# SPDX-License-Identifier: MIT-0
---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ linux_security_sshd_service_name }}"
    state: restarted
  become: true

- name: Restart Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true
