#SPDX-License-Identifier: MIT-0
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ security_apt_cache_valid_time }}"
  become: true

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ security_auto_updates_packages }}"
    state: present
  become: true

- name: Enable automatic apt updates
  ansible.builtin.copy:
    dest: "{{ security_auto_updates_config_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Unmask unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    masked: false
  become: true

- name: Ensure unattended-upgrades is enabled and running
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
    state: started
  become: true
