# SPDX-License-Identifier: MIT-0
---
- name: Include package setup tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include Neovim install tasks
  ansible.builtin.import_tasks: bob.yml
  when: linux_dev_configs_install_bob | bool

- name: Include dotfile repository pull tasks
  ansible.builtin.import_tasks: dotfiles.yml
  when: linux_dev_configs_install_dotfiles | bool

- name: Include user configuration tasks
  ansible.builtin.import_tasks: configs.yml
