# SPDX-License-Identifier: MIT-0
---
linux_neovim_packages:
  - curl
  - git
  - unzip
  - build-essential
  - fd-find
  - ripgrep
  - lazygit
  - fzf
  - tree-sitter-cli
  - zsh
  - tmux

linux_neovim_remove_apt: true

linux_neovim_install_bob: true
linux_neovim_install_dotfiles: true

linux_neovim_bob_install_url: "https://raw.githubusercontent.com/MordechaiHadad/bob/master/scripts/install.sh"
linux_neovim_version: "0.11.2"
linux_neovim_configure_path: true

linux_neovim_dotfiles_repo: "https://github.com/notseekeru/nvim.git"
linux_neovim_dotfiles_version: "main"
linux_neovim_dotfiles_update: true
linux_neovim_dotfiles_dest: "{{ linux_neovim_dev_user_home }}/.config/nvim"

linux_neovim_dev_user: "{{ ansible_facts['user_id'] | default(ansible_facts['user']) }}"
linux_neovim_dev_user_home: "{{ ansible_facts['user_dir'] }}"
linux_neovim_dev_set_shell: true
linux_neovim_dev_shell_path: /bin/zsh

linux_neovim_dev_git_configure: true

linux_neovim_dev_inputrc_ignore_case: true
linux_neovim_dev_vimrc_enable: true

linux_neovim_dev_shell_alias_files:
  - .bash_aliases
