# SPDX-License-Identifier: MIT-0
---
- name: Ensure bob install directory exists
  ansible.builtin.file:
    path: "{{ linux_neovim_dev_user_home }}/.cache"
    state: directory
    mode: "0755"
  become: false

- name: Download bob install script
  ansible.builtin.get_url:
    url: "{{ linux_neovim_bob_install_url }}"
    dest: "{{ linux_neovim_dev_user_home }}/.cache/bob-install.sh"
    mode: "0755"
  become: false

- name: Install bob
  ansible.builtin.command:
    cmd: "{{ linux_neovim_dev_user_home }}/.cache/bob-install.sh"
  args:
    creates: "{{ linux_neovim_dev_user_home }}/.local/bin/bob"
  become: false

- name: Install Neovim version {{ linux_neovim_version }}
  ansible.builtin.command:
    cmd: "{{ linux_neovim_dev_user_home }}/.local/bin/bob install {{ linux_neovim_version }}"
  environment:
    PATH: "{{ linux_neovim_dev_user_home }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  args:
    creates: "{{ linux_neovim_dev_user_home }}/.local/share/bob/v{{ linux_neovim_version }}"
  become: false

- name: Stat the currently active bob Neovim symlink
  ansible.builtin.stat:
    path: "{{ linux_neovim_dev_user_home }}/.local/share/bob/current"
  register: bob_current_symlink
  become: false

- name: Select Neovim version {{ linux_neovim_version }}
  ansible.builtin.command:
    cmd: "{{ linux_neovim_dev_user_home }}/.local/bin/bob use {{ linux_neovim_version }}"
  environment:
    PATH: "{{ linux_neovim_dev_user_home }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  register: bob_use_output
  when: >
    not bob_current_symlink.stat.exists or  not (bob_current_symlink.stat.lnk_target | default('') is search(linux_neovim_version))
  changed_when: >
    "already" not in bob_use_output.stdout and
    "current" not in bob_use_output.stdout
  become: false

- name: Pull Neovim dotfiles
  ansible.builtin.git:
    repo: "{{ linux_neovim_dotfiles_repo }}"
    dest: "{{ linux_neovim_dotfiles_dest }}"
    version: "{{ linux_neovim_dotfiles_version }}"
    update: "{{ linux_neovim_dotfiles_update }}"
    force: true
  become: false
  environment:
    GITHUB_TOKEN: "{{ linux_neovim_github_token }}"
  when: linux_neovim_install_dotfiles | bool
