# SPDX-License-Identifier: MIT-0
---
- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ linux_neovim_dev_user }}"
    shell: "{{ linux_neovim_dev_shell_path }}"
  become: true
  when: linux_neovim_dev_set_shell | bool

- name: Set inputrc to ignore case for tab completion
  ansible.builtin.template:
    src: inputrc.j2
    dest: "{{ linux_neovim_dev_user_home }}/.inputrc"
    mode: "0644"
  become: false
  when: linux_neovim_dev_inputrc_ignore_case | bool

- name: Set Vim configuration
  ansible.builtin.template:
    src: vimrc.j2
    dest: "{{ linux_neovim_dev_user_home }}/.vimrc"
    mode: "0644"
  become: false
  when: linux_neovim_dev_vimrc_enable | bool

- name: Configure shell aliases
  ansible.builtin.template:
    src: aliases.j2
    dest: "{{ linux_neovim_dev_user_home }}/{{ item }}"
    mode: "0644"
  loop: "{{ linux_neovim_dev_shell_alias_files }}"
  become: false
  when: linux_neovim_dev_shell_alias_files | length > 0

- name: Deploy managed .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ linux_neovim_dev_user_home }}/.zshrc"
    mode: "0644"
  become: false

- name: Deploy managed .tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ linux_neovim_dev_user_home }}/.tmux.conf"
    mode: "0644"
  become: false

- name: Deploy managed .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ linux_neovim_dev_user_home }}/.gitconfig"
    mode: "0644"
  become: false
  when: linux_neovim_dev_git_configure | bool

- name: Securely deploy GitHub PAT to local environment file
  ansible.builtin.template:
    src: github_env.j2
    dest: "{{ linux_neovim_dev_user_home }}/.github_env"
    mode: "0600" # Strict read/write permissions for your user only
  become: false
  when: linux_neovim_github_token | length > 0

- name: Ensure GitHub environment is sourced in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ linux_neovim_dev_user_home }}/.zshrc"
    line: "source {{ linux_neovim_dev_user_home }}/.github_env"
    state: present
    insertafter: EOF
  become: false
  when: linux_neovim_github_token | length > 0
