#SPDX-License-Identifier: MIT-0
---
- name: Include package setup tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include Neovim install tasks
  ansible.builtin.import_tasks: bob.yml
  when: neovim_install_bob | bool

- name: Include user configuration tasks
  ansible.builtin.import_tasks: configs.yml
