# SPDX-License-Identifier: MIT-0
---
linux_security_enable_baseline: true
linux_security_enable_authorized_keys: true
linux_security_enable_sshd_hardening: true
linux_security_enable_ufw: true
linux_security_disable_cloud_init_ssh_override: true
linux_security_disable_avahi: true

linux_security_apt_cache_valid_time: 3600
linux_security_auto_updates_packages:
  - unattended-upgrades
  - apt-listchanges
  - ufw
  - curl
  - gnupg2
  - openssh-server
linux_security_auto_updates_config_path: /etc/apt/apt.conf.d/20auto-upgrades

linux_security_authorized_key_user: "seeker"
linux_security_authorized_key_file: "authorized_keys.pub"

linux_security_sshd_config_path: /etc/ssh/sshd_config
linux_security_sshd_validate_cmd: "/usr/sbin/sshd -t -f %s"
linux_security_sshd_service_name: ssh
linux_security_sshd_listen_address: "0.0.0.0"
linux_security_sshd_allow_users:
  - "seeker"
linux_security_sshd_permit_root_login: "no"
linux_security_sshd_password_authentication: "no"
linux_security_sshd_pubkey_authentication: "yes"
linux_security_sshd_max_auth_tries: 3
linux_security_sshd_allow_tcp_forwarding: "no"
linux_security_sshd_x11_forwarding: "no"

linux_security_ufw_ssh_port: "{{ ansible_port | default(22) }}"
linux_security_ufw_allow_interfaces:
  - tailscale0
linux_security_ufw_deny_interfaces:
  - eth0
  - wlan0
linux_security_enable_goss: true
linux_security_goss_version: "v0.4.9"
linux_security_goss_arch: "amd64"
linux_security_goss_dl_url: "https://github.com/goss-org/goss/releases/download/{{ linux_security_goss_version }}/goss-linux-{{ linux_security_goss_arch }}"
linux_security_goss_dgoss_dl_url: "https://github.com/goss-org/goss/releases/download/{{ linux_security_goss_version }}/dgoss"

linux_security_enable_fail2ban: true

linux_security_fail2ban_ignore_ip:
  - 127.0.0.1/8
linux_security_fail2ban_bantime: 1h
linux_security_fail2ban_findtime: 10m
linux_security_fail2ban_maxretry: 5

linux_security_ufw_default_incoming_policy: deny
