---
- name: Debian Hardening for Tailscale Pi Nodes
  hosts: tailscale_pi_nodes
  gather_facts: true

  vars_files:
    - ../group_vars/vault.yml

  # This playbook is responsible for hardening the security of the Raspberry Pi nodes.

  roles:
    - role: security_hardening
