---
- name: Deploy Neovim for debian based systems
  hosts: tailscale_pi_nodes
  become: true
  gather_facts: true

  vars_files:
    - ../group_vars/vault.yml

  tasks:
    - name: "Neovim bob"
      ansible.builtin.import_role:
        name: neovim-bob
